/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLineDetailsApiModel : Information about a line.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLineDetailsApiModel
{
    /// The line name.
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The Product Line name.
    #[serde(
        rename = "detailName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub detail_name: Option<Option<String>>,
    /// The background color of the line symbol.
    #[serde(
        rename = "backgroundColor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub background_color: Option<Option<String>>,
    /// The foreground color of the line symbol.
    #[serde(
        rename = "foregroundColor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub foreground_color: Option<Option<String>>,
    /// The border color of the line symbol.
    #[serde(
        rename = "borderColor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub border_color: Option<Option<String>>,
    /// Flag indicating if the line is a Realtime journey.
    #[serde(rename = "isRealtimeJourney", skip_serializing_if = "Option::is_none")]
    pub is_realtime_journey: Option<bool>,
    #[serde(rename = "transportMode", skip_serializing_if = "Option::is_none")]
    pub transport_mode: Option<
        crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportMode,
    >,
    #[serde(rename = "transportSubMode", skip_serializing_if = "Option::is_none")]
    pub transport_sub_mode: Option<
        crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportSubMode,
    >,
}

impl
    VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLineDetailsApiModel
{
    /// Information about a line.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLineDetailsApiModel{
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLineDetailsApiModel {
            name: None,
            detail_name: None,
            background_color: None,
            foreground_color: None,
            border_color: None,
            is_realtime_journey: None,
            transport_mode: None,
            transport_sub_mode: None,
        }
    }
}
