/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPositionsPeriodJourneyPositionApiModel {
    /// Journey reference
    #[serde(rename = "detailsReference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details_reference: Option<Option<String>>,
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPositionsPeriodLineDetailsApiModel>>,
    /// Journey notes
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodNoteApiModel>>>,
    /// Journey name
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Journey direction
    #[serde(rename = "direction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Option<String>>,
    #[serde(rename = "directionDetails", skip_serializing_if = "Option::is_none")]
    pub direction_details: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel>>,
    /// Current latitude of journey
    #[serde(rename = "latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Option<f64>>,
    /// Current longitude of journey
    #[serde(rename = "longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Option<f64>>,
}

impl
    VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPositionsPeriodJourneyPositionApiModel
{
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPositionsPeriodJourneyPositionApiModel{
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPositionsPeriodJourneyPositionApiModel {
            details_reference: None,
            line: None,
            notes: None,
            name: None,
            direction: None,
            direction_details: None,
            latitude: None,
            longitude: None,
        }
    }
}
