/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel : Information about a service journey.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel {
    /// 16-digit Västtrafik service journey gid.
    #[serde(rename = "gid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gid: Option<Option<String>>,
    /// A description of the direction.
    #[serde(rename = "direction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Option<String>>,
    #[serde(rename = "directionDetails", skip_serializing_if = "Option::is_none")]
    pub direction_details: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel>>,
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodLineDetailsApiModel>>,
    /// The coordinates of the service journey.
    #[serde(rename = "serviceJourneyCoordinates", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_journey_coordinates: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodCoordinateApiModel>>>,
    /// All calls on the service journey.
    #[serde(rename = "callsOnServiceJourney", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub calls_on_service_journey: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodCallDetailsApiModel>>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel {
    /// Information about a service journey.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel {
            gid: None,
            direction: None,
            direction_details: None,
            line: None,
            service_journey_coordinates: None,
            calls_on_service_journey: None,
        }
    }
}
