/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyTransportMode : A subset of TransportMode

/// A subset of TransportMode
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyTransportMode {
    #[serde(rename = "tram")]
    Tram,
    #[serde(rename = "bus")]
    Bus,
    #[serde(rename = "ferry")]
    Ferry,
    #[serde(rename = "train")]
    Train,
    #[serde(rename = "taxi")]
    Taxi,
    #[serde(rename = "walk")]
    Walk,
    #[serde(rename = "bike")]
    Bike,
    #[serde(rename = "car")]
    Car,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyTransportMode {
    fn to_string(&self) -> String {
        match self {
            Self::Tram => String::from("tram"),
            Self::Bus => String::from("bus"),
            Self::Ferry => String::from("ferry"),
            Self::Train => String::from("train"),
            Self::Taxi => String::from("taxi"),
            Self::Walk => String::from("walk"),
            Self::Bike => String::from("bike"),
            Self::Car => String::from("car"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyTransportMode {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyTransportMode {
        Self::Tram
    }
}
