/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLinkSegmentApiModel : Represents a segment of a departure access link, arrival access link or destination link.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLinkSegmentApiModel {
    /// Segment name.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "maneuver", skip_serializing_if = "Option::is_none")]
    pub maneuver: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLinkSegmentManeuver>,
    #[serde(rename = "orientation", skip_serializing_if = "Option::is_none")]
    pub orientation: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLinkSegmentOrientation>,
    /// Description for the maneuver.
    #[serde(rename = "maneuverDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub maneuver_description: Option<Option<String>>,
    /// Distance for this segment in meter.
    #[serde(rename = "distanceInMeters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub distance_in_meters: Option<Option<i32>>,
}

impl
    VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLinkSegmentApiModel
{
    /// Represents a segment of a departure access link, arrival access link or destination link.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLinkSegmentApiModel{
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodLinkSegmentApiModel {
            name: None,
            maneuver: None,
            orientation: None,
            maneuver_description: None,
            distance_in_meters: None,
        }
    }
}
