/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTicketSuggestionApiModel : Information about a ticket suggestion.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTicketSuggestionApiModel {
    /// The product id.
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<i32>,
    /// The product name.
    #[serde(rename = "productName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_name: Option<Option<String>>,
    /// The product type.
    #[serde(rename = "productType", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<i32>,
    #[serde(rename = "travellerCategory", skip_serializing_if = "Option::is_none")]
    pub traveller_category: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTravellerCategory>,
    /// The product price in SEK.
    #[serde(rename = "priceInSek", skip_serializing_if = "Option::is_none")]
    pub price_in_sek: Option<f64>,
    #[serde(rename = "timeValidity", skip_serializing_if = "Option::is_none")]
    pub time_validity: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTimeValidityApiModel>>,
    #[serde(rename = "timeLimitation", skip_serializing_if = "Option::is_none")]
    pub time_limitation: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeLimitation>,
    /// A list of the channels that sell the product.
    #[serde(rename = "saleChannels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sale_channels: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodChannelApiModel>>>,
    /// A list of the valid zones for the ticket.
    #[serde(rename = "validZones", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub valid_zones: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodZoneApiModel>>>,
    #[serde(rename = "productInstanceType", skip_serializing_if = "Option::is_none")]
    pub product_instance_type: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductInstanceTypeApiModel>,
    #[serde(rename = "punchConfiguration", skip_serializing_if = "Option::is_none")]
    pub punch_configuration: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodPunchConfigurationApiModel>>,
    /// Used to get ticket offer.
    #[serde(rename = "offerSpecification", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub offer_specification: Option<Option<String>>,
    #[serde(rename = "areaType", skip_serializing_if = "Option::is_none")]
    pub area_type: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAreaType>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTicketSuggestionApiModel {
    /// Information about a ticket suggestion.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTicketSuggestionApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTicketSuggestionApiModel {
            product_id: None,
            product_name: None,
            product_type: None,
            traveller_category: None,
            price_in_sek: None,
            time_validity: None,
            time_limitation: None,
            sale_channels: None,
            valid_zones: None,
            product_instance_type: None,
            punch_configuration: None,
            offer_specification: None,
            area_type: None,
        }
    }
}
