/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityType : Different types of time validity.

/// Different types of time validity.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "amountunit")]
    Amountunit,
    #[serde(rename = "fromtodate")]
    Fromtodate,
    #[serde(rename = "fromtodatetime")]
    Fromtodatetime,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Amountunit => String::from("amountunit"),
            Self::Fromtodate => String::from("fromtodate"),
            Self::Fromtodatetime => String::from("fromtodatetime"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityType {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityType {
        Self::Unknown
    }
}
