/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationType : Represents the different types of location.

/// Represents the different types of location.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "stoparea")]
    Stoparea,
    #[serde(rename = "stoppoint")]
    Stoppoint,
    #[serde(rename = "address")]
    Address,
    #[serde(rename = "pointofinterest")]
    Pointofinterest,
    #[serde(rename = "metastation")]
    Metastation,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Stoparea => String::from("stoparea"),
            Self::Stoppoint => String::from("stoppoint"),
            Self::Address => String::from("address"),
            Self::Pointofinterest => String::from("pointofinterest"),
            Self::Metastation => String::from("metastation"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationType {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationType {
        Self::Unknown
    }
}
