/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportSubMode : Represents the different types of sub transport modes.

/// Represents the different types of sub transport modes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportSubMode {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "vasttagen")]
    Vasttagen,
    #[serde(rename = "longdistancetrain")]
    Longdistancetrain,
    #[serde(rename = "regionaltrain")]
    Regionaltrain,
    #[serde(rename = "flygbussarna")]
    Flygbussarna,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportSubMode {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::None => String::from("none"),
            Self::Vasttagen => String::from("vasttagen"),
            Self::Longdistancetrain => String::from("longdistancetrain"),
            Self::Regionaltrain => String::from("regionaltrain"),
            Self::Flygbussarna => String::from("flygbussarna"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportSubMode {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportSubMode {
        Self::Unknown
    }
}
