/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel
{
    /// The 16-digit Västtrafik gid of the stop point.
    #[serde(rename = "gid")]
    pub gid: String,
    /// The stop point name.
    #[serde(rename = "name")]
    pub name: String,
    /// The platform of the stop point.
    #[serde(
        rename = "platform",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub platform: Option<Option<String>>,
    /// The latitude coordinate of the stop point.
    #[serde(
        rename = "latitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub latitude: Option<Option<f64>>,
    /// The longitude coordinate of the stop point.
    #[serde(
        rename = "longitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub longitude: Option<Option<f64>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel {
    pub fn new(gid: String, name: String) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel {
            gid,
            name,
            platform: None,
            latitude: None,
            longitude: None,
        }
    }
}
