/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodGetArrivalsResponse : The response to a get arrivals request, includes the results and pagination information.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodGetArrivalsResponse {
    /// The results.
    #[serde(rename = "results", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub results: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodArrivalApiModel>>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPaginationProperties>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPaginationLinks>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodGetArrivalsResponse {
    /// The response to a get arrivals request, includes the results and pagination information.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodGetArrivalsResponse {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodGetArrivalsResponse {
            results: None,
            pagination: None,
            links: None,
        }
    }
}
