/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodStopAreasPeriodStopAreaApiModel
{
    /// The 16-digit Västtrafik gid of the stop area.
    #[serde(
        rename = "gid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub gid: Option<Option<String>>,
    /// The stop area name.
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The latitude of the stop point.
    #[serde(rename = "lat", skip_serializing_if = "Option::is_none")]
    pub lat: Option<f64>,
    /// The longitude of the stop point.
    #[serde(rename = "long", skip_serializing_if = "Option::is_none")]
    pub long: Option<f64>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodStopAreasPeriodStopAreaApiModel {
    pub fn new(
    ) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodStopAreasPeriodStopAreaApiModel
    {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodStopAreasPeriodStopAreaApiModel {
            gid: None,
            name: None,
            lat: None,
            long: None,
        }
    }
}
