/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAreaType : The type of area for a set of zones.

/// The type of area for a set of zones.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAreaType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "mini")]
    Mini,
    #[serde(rename = "extra")]
    Extra,
    #[serde(rename = "leisure")]
    Leisure,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAreaType {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("none"),
            Self::Standard => String::from("standard"),
            Self::Mini => String::from("mini"),
            Self::Extra => String::from("extra"),
            Self::Leisure => String::from("leisure"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAreaType {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAreaType {
        Self::None
    }
}
