/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAgeType : Different types of age types for a product.

/// Different types of age types for a product.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAgeType {
    #[serde(rename = "adult")]
    Adult,
    #[serde(rename = "youth")]
    Youth,
    #[serde(rename = "senior")]
    Senior,
    #[serde(rename = "schoolyouth")]
    Schoolyouth,
    #[serde(rename = "other")]
    Other,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAgeType {
    fn to_string(&self) -> String {
        match self {
            Self::Adult => String::from("adult"),
            Self::Youth => String::from("youth"),
            Self::Senior => String::from("senior"),
            Self::Schoolyouth => String::from("schoolyouth"),
            Self::Other => String::from("other"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAgeType {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAgeType {
        Self::Adult
    }
}
