/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDepartureDetailsIncludeType : The different kinds of detailed information that could be included in a get departure details request.

/// The different kinds of detailed information that could be included in a get departure details request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDepartureDetailsIncludeType {
    #[serde(rename = "servicejourneycalls")]
    Servicejourneycalls,
    #[serde(rename = "servicejourneycoordinates")]
    Servicejourneycoordinates,
    #[serde(rename = "occupancy")]
    Occupancy,
}

impl ToString
    for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDepartureDetailsIncludeType
{
    fn to_string(&self) -> String {
        match self {
            Self::Servicejourneycalls => String::from("servicejourneycalls"),
            Self::Servicejourneycoordinates => String::from("servicejourneycoordinates"),
            Self::Occupancy => String::from("occupancy"),
        }
    }
}

impl Default
    for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDepartureDetailsIncludeType
{
    fn default(
    ) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDepartureDetailsIncludeType {
        Self::Servicejourneycalls
    }
}
