/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodDepartureApiModel {
    /// A reference that should be used when getting detailed information about the journey.
    #[serde(rename = "detailsReference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details_reference: Option<Option<String>>,
    #[serde(rename = "serviceJourney", skip_serializing_if = "Option::is_none")]
    pub service_journey: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyApiModel>>,
    #[serde(rename = "stopPoint")]
    pub stop_point: Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel>,
    #[serde(rename = "realtimeStopPoint", skip_serializing_if = "Option::is_none")]
    pub realtime_stop_point: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel>>,
    /// The planned time of the call in RFC 3339 format.
    #[serde(rename = "plannedTime")]
    pub planned_time: String,
    /// The estimated time of the call in RFC 3339 format.
    #[serde(rename = "estimatedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub estimated_time: Option<Option<String>>,
    /// The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.
    #[serde(rename = "estimatedOtherwisePlannedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub estimated_otherwise_planned_time: Option<Option<String>>,
    /// Flag indicating if the departure or arrival is cancelled.
    #[serde(rename = "isCancelled", skip_serializing_if = "Option::is_none")]
    pub is_cancelled: Option<bool>,
    /// Flag indicating if the departure or arrival is partially cancelled.
    #[serde(rename = "isPartCancelled", skip_serializing_if = "Option::is_none")]
    pub is_part_cancelled: Option<bool>,
    #[serde(rename = "occupancy", skip_serializing_if = "Option::is_none")]
    pub occupancy: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodOccupancyInformationApiModel>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodDepartureApiModel {
    pub fn new(stop_point: crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodStopPointApiModel, planned_time: String) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodDepartureApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodDepartureApiModel {
            details_reference: None,
            service_journey: None,
            stop_point: Box::new(stop_point),
            realtime_stop_point: None,
            planned_time,
            estimated_time: None,
            estimated_otherwise_planned_time: None,
            is_cancelled: None,
            is_part_cancelled: None,
            occupancy: None,
        }
    }
}
