/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTimeValidityApiModel : Information about the time validity of a ticket suggestion.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTimeValidityApiModel
{
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<
        crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityType,
    >,
    /// The amount of the unit specified by the Unit property. Always used together with the Unit property.
    #[serde(
        rename = "amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub amount: Option<Option<i32>>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<
        crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityUnit,
    >,
    /// The from date of a date interval specified in RFC 3339 format. Always used together with the  ToDate property.
    #[serde(
        rename = "fromDate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_date: Option<Option<String>>,
    /// The to date of a date interval specified in RFC 3339 format. Always used together with the  FromDate property.
    #[serde(
        rename = "toDate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub to_date: Option<Option<String>>,
    /// The from time of a datetime interval specified in RFC 3339 format. Always used together with  the ToDateTime property.
    #[serde(
        rename = "fromDateTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_date_time: Option<Option<String>>,
    /// The to time of a datetime interval specified in RFC 3339 format. Always used together with  the FromDateTime property.
    #[serde(
        rename = "toDateTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub to_date_time: Option<Option<String>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTimeValidityApiModel {
    /// Information about the time validity of a ticket suggestion.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTimeValidityApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTimeValidityApiModel {
            r#type: None,
            amount: None,
            unit: None,
            from_date: None,
            to_date: None,
            from_date_time: None,
            to_date_time: None,
        }
    }
}
