/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductTypeEnum : Different types of products.

/// Different types of products.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductTypeEnum {
    #[serde(rename = "single")]
    Single,
    #[serde(rename = "period")]
    Period,
    #[serde(rename = "shortterm")]
    Shortterm,
    #[serde(rename = "school")]
    School,
    #[serde(rename = "event")]
    Event,
    #[serde(rename = "flex")]
    Flex,
    #[serde(rename = "seasonal")]
    Seasonal,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Single => String::from("single"),
            Self::Period => String::from("period"),
            Self::Shortterm => String::from("shortterm"),
            Self::School => String::from("school"),
            Self::Event => String::from("event"),
            Self::Flex => String::from("flex"),
            Self::Seasonal => String::from("seasonal"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductTypeEnum {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductTypeEnum {
        Self::Single
    }
}
