/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketSpecificationApiModel {
    #[serde(rename = "ticketName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ticket_name: Option<Option<String>>,
    #[serde(rename = "configurations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub configurations: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketConfigurationApiModel>>>,
    #[serde(rename = "productType", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductTypeEnum>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketSpecificationApiModel {
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketSpecificationApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketSpecificationApiModel {
            ticket_name: None,
            configurations: None,
            product_type: None,
        }
    }
}
