/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopAreaApiModel {
    /// The 16-digit Västtrafik gid of the stop area.
    #[serde(rename = "gid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gid: Option<Option<String>>,
    /// The stop area name.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// The latitude of the stop point.
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// The longitude of the stop point.
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[serde(rename = "tariffZone1", skip_serializing_if = "Option::is_none")]
    pub tariff_zone1: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodTariffZoneApiModel>>,
    #[serde(rename = "tariffZone2", skip_serializing_if = "Option::is_none")]
    pub tariff_zone2: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodTariffZoneApiModel>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopAreaApiModel {
    pub fn new(
    ) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopAreaApiModel
    {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopAreaApiModel {
            gid: None,
            name: None,
            latitude: None,
            longitude: None,
            tariff_zone1: None,
            tariff_zone2: None,
        }
    }
}
