/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPunchConfigurationDurationUnitApiModel : Unit of duration of validity of a single punch.

/// Unit of duration of validity of a single punch.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPunchConfigurationDurationUnitApiModel
{
    #[serde(rename = "hours")]
    Hours,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPunchConfigurationDurationUnitApiModel {
    fn to_string(&self) -> String {
        match self {
            Self::Hours => String::from("hours"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPunchConfigurationDurationUnitApiModel {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPunchConfigurationDurationUnitApiModel {
        Self::Hours
    }
}
