/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodCorePeriodModelsPeriodDateTimeRelatesToType {
    #[serde(rename = "departure")]
    Departure,
    #[serde(rename = "arrival")]
    Arrival,
}

impl ToString for VtPeriodApiPlaneraResaPeriodCorePeriodModelsPeriodDateTimeRelatesToType {
    fn to_string(&self) -> String {
        match self {
            Self::Departure => String::from("departure"),
            Self::Arrival => String::from("arrival"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodCorePeriodModelsPeriodDateTimeRelatesToType {
    fn default() -> VtPeriodApiPlaneraResaPeriodCorePeriodModelsPeriodDateTimeRelatesToType {
        Self::Departure
    }
}
