/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationByTextType : A subset of LocationType

/// A subset of LocationType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationByTextType {
    #[serde(rename = "stoparea")]
    Stoparea,
    #[serde(rename = "address")]
    Address,
    #[serde(rename = "pointofinterest")]
    Pointofinterest,
    #[serde(rename = "metastation")]
    Metastation,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationByTextType {
    fn to_string(&self) -> String {
        match self {
            Self::Stoparea => String::from("stoparea"),
            Self::Address => String::from("address"),
            Self::Pointofinterest => String::from("pointofinterest"),
            Self::Metastation => String::from("metastation"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationByTextType {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodLocationByTextType {
        Self::Stoparea
    }
}
