/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodPunchConfigurationDurationApiModel : Describes the duration of validity of a single punch.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodPunchConfigurationDurationApiModel {
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodPunchConfigurationDurationUnitApiModel>,
    /// Duration of validity of a single punch.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<i32>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodPunchConfigurationDurationApiModel {
    /// Describes the duration of validity of a single punch.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodPunchConfigurationDurationApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodPunchConfigurationDurationApiModel {
            unit: None,
            amount: None,
        }
    }
}
