/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel : Contains detailed information about a direction and its components.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel {
    /// The original direction string.
    #[serde(
        rename = "fullDirection",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub full_direction: Option<Option<String>>,
    /// The direction string after parsing and removing the different components.
    #[serde(
        rename = "shortDirection",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub short_direction: Option<Option<String>>,
    /// The name of the replaced line, if any. Parses and replaces the following component: \", Ersätter [replaces]\"
    #[serde(
        rename = "replaces",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub replaces: Option<Option<String>>,
    /// The name of the via location, if any. Parses and replaces the following component: \", via [via]\"
    #[serde(
        rename = "via",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub via: Option<Option<String>>,
    /// Whether the service is free. Parses and replaces the following component: \", Fri resa\"
    #[serde(
        rename = "isFreeService",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_free_service: Option<Option<bool>>,
    /// Whether the service is paid. Parses and replaces the following component: \", Avgiftsbelagd tur\"
    #[serde(
        rename = "isPaidService",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_paid_service: Option<Option<bool>>,
    /// Whether the service is a swimming service. Parses and replaces the following component: \", Badbuss\"
    #[serde(
        rename = "isSwimmingService",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_swimming_service: Option<Option<bool>>,
    /// Whether the service is a direct destination bus. Parses and replaces the following component: \", Direktbuss\"
    #[serde(
        rename = "isDirectDestinationBus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_direct_destination_bus: Option<Option<bool>>,
    /// Whether the service has front entry. Parses and replaces the following component: \", Påstigning fram\"
    #[serde(
        rename = "isFrontEntry",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_front_entry: Option<Option<bool>>,
    /// Whether the service is an extra bus. Parses and replaces the following component: \", Extrabuss\"
    #[serde(
        rename = "isExtraBus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_extra_bus: Option<Option<bool>>,
    /// Whether the service is an extra boat. Parses and replaces the following component: \", Extrabåt\"
    #[serde(
        rename = "isExtraBoat",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_extra_boat: Option<Option<bool>>,
    /// Whether the service is an extra tram. Parses and replaces the following component: \", Extravagn\"
    #[serde(
        rename = "isExtraTram",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_extra_tram: Option<Option<bool>>,
    /// Whether the service is a school bus. Parses and replaces the following component: \", Skolbuss\"
    #[serde(
        rename = "isSchoolBus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_school_bus: Option<Option<bool>>,
    /// Whether the service is an express bus. Parses and replaces the following component: \", Snabbuss\"
    #[serde(
        rename = "isExpressBus",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_express_bus: Option<Option<bool>>,
    /// The name of the fortified line, if any. Parses and replaces the following component: \", Fortifies [fortifies]\"
    #[serde(
        rename = "fortifiesLine",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fortifies_line: Option<Option<String>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel {
    /// Contains detailed information about a direction and its components.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel
    {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel {
            full_direction: None,
            short_direction: None,
            replaces: None,
            via: None,
            is_free_service: None,
            is_paid_service: None,
            is_swimming_service: None,
            is_direct_destination_bus: None,
            is_front_entry: None,
            is_extra_bus: None,
            is_extra_boat: None,
            is_extra_tram: None,
            is_school_bus: None,
            is_express_bus: None,
            fortifies_line: None,
        }
    }
}
