/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodCallApiModel : Information about a call on the trip leg.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodCallApiModel {
    #[serde(rename = "stopPoint")]
    pub stop_point: Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopPointApiModel>,
    #[serde(rename = "realtimeStopPoint", skip_serializing_if = "Option::is_none")]
    pub realtime_stop_point: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopPointApiModel>>,
    /// The planned time of the call in RFC 3339 format.
    #[serde(rename = "plannedTime")]
    pub planned_time: String,
    /// The estimated time of the call in RFC 3339 format.
    #[serde(rename = "estimatedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub estimated_time: Option<Option<String>>,
    /// The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.
    #[serde(rename = "estimatedOtherwisePlannedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub estimated_otherwise_planned_time: Option<Option<String>>,
    /// An ordered list (most important first) of notes related to the call.
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodNoteApiModel>>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodCallApiModel {
    /// Information about a call on the trip leg.
    pub fn new(
        stop_point: crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodStopPointApiModel,
        planned_time: String,
    ) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodCallApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneysPeriodCallApiModel {
            stop_point: Box::new(stop_point),
            realtime_stop_point: None,
            planned_time,
            estimated_time: None,
            estimated_otherwise_planned_time: None,
            notes: None,
        }
    }
}
