/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodApiError : Information about the error.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodApiError {
    /// Error code.
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<i32>,
    /// More detailed description of the error.
    #[serde(
        rename = "errorMessage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_message: Option<Option<String>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodApiError {
    /// Information about the error.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodApiError {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodApiError {
            error_code: None,
            error_message: None,
        }
    }
}
