/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyApiModel : Information about a service journey of a departure or arrival.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyApiModel {
    /// 16-digit Västtrafik service journey gid.
    #[serde(rename = "gid")]
    pub gid: String,
    /// A description of the origin.
    #[serde(rename = "origin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Option<String>>,
    /// A description of the direction.
    #[serde(rename = "direction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Option<String>>,
    #[serde(rename = "directionDetails", skip_serializing_if = "Option::is_none")]
    pub direction_details: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDirectionDetailsApiModel>>,
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodLineApiModel>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyApiModel {
    /// Information about a service journey of a departure or arrival.
    pub fn new(gid: String) -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodDeparturesAndArrivalsPeriodServiceJourneyApiModel {
            gid,
            origin: None,
            direction: None,
            direction_details: None,
            line: None,
        }
    }
}
