/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketConfigurationApiModel
{
    #[serde(
        rename = "productId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub product_id: Option<Option<i32>>,
    #[serde(rename = "validityLength", skip_serializing_if = "Option::is_none")]
    pub validity_length: Option<i32>,
    #[serde(rename = "itemPrice", skip_serializing_if = "Option::is_none")]
    pub item_price: Option<f64>,
    #[serde(
        rename = "offerSpecification",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub offer_specification: Option<Option<String>>,
    #[serde(rename = "ageType", skip_serializing_if = "Option::is_none")]
    pub age_type:
        Option<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodAgeType>,
    #[serde(
        rename = "zoneIds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub zone_ids: Option<Option<Vec<String>>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketConfigurationApiModel {
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketConfigurationApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodProductsPeriodTicketConfigurationApiModel {
            product_id: None,
            validity_length: None,
            item_price: None,
            offer_specification: None,
            age_type: None,
            zone_ids: None,
        }
    }
}
