/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportMode : Represents the different types of transport modes.

/// Represents the different types of transport modes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportMode {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "tram")]
    Tram,
    #[serde(rename = "bus")]
    Bus,
    #[serde(rename = "ferry")]
    Ferry,
    #[serde(rename = "train")]
    Train,
    #[serde(rename = "taxi")]
    Taxi,
    #[serde(rename = "walk")]
    Walk,
    #[serde(rename = "bike")]
    Bike,
    #[serde(rename = "car")]
    Car,
    #[serde(rename = "teletaxi")]
    Teletaxi,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportMode {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::None => String::from("none"),
            Self::Tram => String::from("tram"),
            Self::Bus => String::from("bus"),
            Self::Ferry => String::from("ferry"),
            Self::Train => String::from("train"),
            Self::Taxi => String::from("taxi"),
            Self::Walk => String::from("walk"),
            Self::Bike => String::from("bike"),
            Self::Car => String::from("car"),
            Self::Teletaxi => String::from("teletaxi"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportMode {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTransportMode {
        Self::Unknown
    }
}
