/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityUnit : Different types of unit that specifies the amount of the Amount property.

/// Different types of unit that specifies the amount of the Amount property.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityUnit {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "minutes")]
    Minutes,
    #[serde(rename = "hours")]
    Hours,
    #[serde(rename = "days")]
    Days,
    #[serde(rename = "year")]
    Year,
    #[serde(rename = "semester")]
    Semester,
    #[serde(rename = "schoolyear")]
    Schoolyear,
    #[serde(rename = "unlimited")]
    Unlimited,
}

impl ToString for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityUnit {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Minutes => String::from("minutes"),
            Self::Hours => String::from("hours"),
            Self::Days => String::from("days"),
            Self::Year => String::from("year"),
            Self::Semester => String::from("semester"),
            Self::Schoolyear => String::from("schoolyear"),
            Self::Unlimited => String::from("unlimited"),
        }
    }
}

impl Default for VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityUnit {
    fn default() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodTimeValidityUnit {
        Self::Unknown
    }
}
