/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodJourneyDetailsApiModel : Detailed information about a journey.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodJourneyDetailsApiModel {
    #[serde(rename = "departureAccessLink", skip_serializing_if = "Option::is_none")]
    pub departure_access_link: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodDepartureAccessLinkApiModel>>,
    /// Detailed information, including stops, about the trip legs.
    #[serde(rename = "tripLegs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trip_legs: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTripLegDetailsApiModel>>>,
    /// A list of ConnectionLinks between TripLegs, when applicable. The internal order of TripLegs and ConnectionLinks is defined by Index-property on the objects.
    #[serde(rename = "connectionLinks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub connection_links: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodConnectionLinkApiModel>>>,
    #[serde(rename = "arrivalAccessLink", skip_serializing_if = "Option::is_none")]
    pub arrival_access_link: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodArrivalAccessLinkApiModel>>,
    #[serde(rename = "destinationLink", skip_serializing_if = "Option::is_none")]
    pub destination_link: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodDestinationLinkApiModel>>,
    #[serde(rename = "ticketSuggestionsResult", skip_serializing_if = "Option::is_none")]
    pub ticket_suggestions_result: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTicketSuggestionsResultApiModel>>,
    /// The tariff zones that the journey traverses.
    #[serde(rename = "tariffZones", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tariff_zones: Option<Option<Vec<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodTariffZoneApiModel>>>,
    #[serde(rename = "occupancy", skip_serializing_if = "Option::is_none")]
    pub occupancy: Option<Box<crate::models::VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodOccupancyInformationApiModel>>,
}

impl VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodJourneyDetailsApiModel {
    /// Detailed information about a journey.
    pub fn new() -> VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodJourneyDetailsApiModel {
        VtPeriodApiPlaneraResaPeriodWebPeriodV4PeriodModelsPeriodJourneyDetailsPeriodJourneyDetailsApiModel {
            departure_access_link: None,
            trip_legs: None,
            connection_links: None,
            arrival_access_link: None,
            destination_link: None,
            ticket_suggestions_result: None,
            tariff_zones: None,
            occupancy: None,
        }
    }
}
